sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_87315c79d9de_key -iv $encrypted_87315c79d9de_iv -in multi-k8s-course-project-5c3d20db9930.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  
  - gcloud config set project multi-k8s-course-project
  - gcloud config set compute/zone europe-west4-b 
  - gcloud container clusters get-credentials mulit-k8s-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t georgetatsis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true georgetatsis/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleaup: true 
  on:
    branch: master